from math import *
import csv
from aminoacids import *

###############
# DESCRIPTION #
###############
"""
This file serves to generate 3 matrices based on substitution 
frequencies, given polar/nonpolar flanks. The script requires 
import from a substitution matrix csv file generated by matrixgen.py

Author Yolanda Shen

IN PROGRESS
"""

# Variables to be modified
sub_csv = 'C:/Users/yolan/Documents/Holmes/prot_align/matrices/sub_matrix.csv'
polar_csv_file = 'C:/Users/yolan/Documents/Holmes/prot_align/matrices/polar_matrix.csv'
nonpolar_csv_file = 'C:/Users/yolan/Documents/Holmes/prot_align/matrices/nonpolar_matrix.csv'
combo_csv_file = 'C:/Users/yolan/Documents/Holmes/prot_align/matrices/combo_polar_matrix.csv'
generate_polar_csv = False
generate_nonpolar_csv = False
generate_combo_csv = False

#############################################
# Do not modify anything below this comment #
#############################################

def csv_aggregator():
    global polar_matrix
    csv_reader.__next__()
    for row in csv_reader:
        lflank = row[0]
        mid = row[1]
        rflank = row[2]
        sub = row[3]
        count = int(row[4])
        key = mid + sub
        if lflank in polar and rflank in polar:
            if key not in polar_matrix.keys() :
                polar_matrix[key] = count
            else:
                polar_matrix[key] += count
        elif lflank not in polar and rflank not in polar:
            if key not in nonpolar_matrix.keys() :
                nonpolar_matrix[key] = count
            else:
                nonpolar_matrix[key] += count
        else:
            if key not in combo_matrix.keys() :
                combo_matrix[key] = count
            else:
                combo_matrix[key] += count

# Writes the generated matrix to a CSV file
def write_to_csv(matrix, csv_file, bool):
    if not bool:
        return
    with open(csv_file, 'w') as f:
        for key in matrix.keys():
            if key == 'type':
                f.write("Parent,Sub,Count")
            else:
                f.write("%s,%s,%s,\n" % (key[0], key[1], matrix[key]))
    print("CSV successfully written.")


csv_reader = csv.reader(open(sub_csv))
polar_matrix = {'type':'polar'}
nonpolar_matrix = {'type':'nonpolar'}
combo_matrix = {'type':'combo'}

csv_aggregator()
write_to_csv(polar_matrix, polar_csv_file, generate_polar_csv)
write_to_csv(nonpolar_matrix, nonpolar_csv_file, generate_nonpolar_csv)
write_to_csv(combo_matrix, combo_csv_file, generate_combo_csv)

print(polar_matrix)

